= La conspiración del sueño no me deja continuar

:hp-tags: aleatorio


Pues estos últimos días me a estado pasando algo muy particular, cada que despierto solo puedo estar activo unas cuantas horas para luego empezar a tener sueño y luego dormir como por 6, 12 horas, no se por que exactamente me pasa eso, pero es algo que me esta empezando a fastidiar, osea no puedo estar despierto un mínimo de tiempo o empezar a querer hacer algo por que de una vez me acuesto a dormir otra vez.... 

Y pues eso es lo que me ha estado atrasando todo este tiempo, pensé que si simplemente dormía esas horas ya se me iba a quitar pero no, simplemente no puedo mantenerme despierto por mucho tiempo, por más que lo intente, ¿a que se deberá esto? Supongo que al saber que ya termine materias mi cuerpo ya no ahora me este pidiendo de vuelta todas esas horas que no dormí si, también he reducido el consumo de gaseosa por lo que quizás pueda ser eso pero no lo se

Y bueno este mal trae consigo también el problema que no puedo avanzar tan rápido como quiero en los dibujos, y es que entre más horas de sueño menos trabajo puedo hacer, espero que este problema se me quite pronto, o si no.... o si no... pues me tomare UN MALDITO GALON DE REDBULL 