= Ausencia 

Wow, tenia un articulo preparado para montar ayer pero el algún motivo todo lo que había escrito no se quiso salvar y entre una cosa y la otra lo perdí todo, bueno la verdad es que tengo mucha pereza en volver a escribir todo lo que había escrito antes, pero aquí unas cosas, la verdad es que debo ser más constante a la hora de escribir artículos en mi blog, ojeando un momento la ultima vez que subí un articulo aquí era noviembre del 2016 y hoy estamos a ¡MARZO! Osea que si me quedo dormido con la tontería publicaba un articulo en noviembre del año siguiente, pero la verdad era muy difícil pensar en algo cuando sientes que tu vida no es tan interesante, digo que podía decir en ese entonces cuando mi rutina se limitaba a moverme a un sitio usar la pc para algo, salir de ese sitio y usar la pc para otra cosa y eso no a cambiado realmente, pero vale uno debe aprender a venderse y si tu no hacer que las cosas luzcan interesantes nadie lo va hacer por ti…

Con esto dicho he estado dibujando más regularmente estos, ehm… la mitad de enero y febrero por que lo que es la otra mitad de esos meses mi PC se le ocurrió la genial idea de dejar de funcionar y estuve prácticamente un maldito mes con ese problema y ahora estoy en mitad del trabajo osea que mis tiempos se han reducido hasta la mitad de lunes a viernes, los fines de semana los mantengo completos, así que mientras mi pc se negaba a existir aproveche el tiempo para arreglar mis horas de sueño por que eso de levantarse a las 5 de la tarde para acostarse a las  7 de la mañana no podría ser sano, así que opte por un método que me enseño un amigo para arreglar ese problema con el cuerpo, no dormir las horas que el cuerpo te lo pide y dormir justo cuando estas se ajusten con el horario regular de sueño, no es la mejor solución y la sensación de estar sin sueño es algo que no me gusta experimentar, todo se siente muy extraño y confuso, pero las buenas noticias, ¡FINALMENTE PUEDO DORMIR A LA HORA QUE ES! Bueno más o menos, siento que ahora me acuesto muy temprano y me levanto aun más temprano aun.

Otra cosa que estado pensando es como aprovechar esas horas del trabajo para dedicarme hacer otra cosa, ya sea hacer un bosquejo un storyboard o algo mientras no tengo nada que hacer, no quiero que sea algo muy complicado por que en cuento ya me acomodo para hacer cualquier cosa surge otra actividad y bueno tengo que atenderla, al menos puedo dedicarle un rato al blog pero ahora que escribo esto se me ocurre otra idea, voy a ver si es viable 

¿que otra cosa he hecho con mi vida?
Pues, me compre el Pokemon Sun, esta chevere el juego pero siento que todo esta muy corto pero fuera de eso esta bastante bien.